export const users = [
    { userId: "u1", userName: "Алексей_1994b" },
    { userId: "u2", userName: "Джунбокс3000" },
    { userId: "u3", userName: "User22354" },
    { userId: "u4", userName: "User2415" },
    { userId: "u6", userName: "User66478" },
    { userId: "u10", userName: "User66473" },
];
export const mockData = [
    {
        id: "c1",
        text: "Самое обидное когда сценарий по сути есть - в виде книг, где нет сюжетных дыр, всё логично, стройное повествование и достаточно взять и экранизировать оригинал как это было в первых фильмах с минимальным количеством отсебятины и зритель с восторгом примет любой такой фильм и сериал, однако вместо этого 'Кольца власти' просто позаимствовали имена из оригинала, куски истории, мало связанные между собой и выдали очередной среднячковый сериал на один раз в лучшем случае.",
        userName: "Алексей_1994b",
        userId: "u1",
        commentType: "comment",
        commentTime: "19.04 15:52",
        commentTimestamp: 1673780100,
        rating: 1,
        like: false,
        raters: [{ userId: "u2", rateState: 1 }],
        answers: ["c2"],
        parentId: null,
    },
    {
        id: "c2",
        text: "Наверное, самая большая ошибка создателей сериала была в том, что они поставили уж слишком много надежд на поддержку фанатов вселенной. Как оказалось на деле, большинство 'фанатов' с самой настоящей яростью и желчью стали уничтожать сериал, при этом объективности в отзывах самый минимум.",
        userName: "Джунбокс3000",
        userId: "u2",
        commentType: "answer",
        commentTime: "19.04 16:47",
        commentTimestamp: 1673785080,
        rating: 0,
        like: false,
        raters: [],
        answers: [],
        parentId: "c1",
    },
    {
        id: "c3",
        text: "И я того же мнения",
        userName: "User22354",
        userId: "u3",
        commentType: "comment",
        commentTime: "19.04 17:15",
        commentTimestamp: 1673788800,
        rating: -1,
        like: false,
        raters: [{ userId: "u6", rateState: -1 }],
        answers: ["c8"],
        parentId: null,
    },
    {
        id: "c8",
        text: "Ну естественно",
        userName: "User66478",
        userId: "u6",
        commentType: "answer",
        commentTime: "19.04 17:29",
        commentTimestamp: 1673790600,
        rating: 0,
        like: false,
        raters: [],
        answers: [],
        parentId: "c3",
    },
    {
        id: "c4",
        text: "Здравствуйте",
        userName: "User66473",
        userId: "u10",
        commentType: "comment",
        commentTime: "19.04 17:30",
        commentTimestamp: 1673790600,
        rating: 0,
        like: false,
        raters: [],
        answers: [],
        parentId: null,
    },
];
